import type { FurnitureItem } from "@/lib/cms/types";
import { legacyMaterials, legacyMediaAssets as media } from "@/lib/cms/legacy-images";

/** Fallback catalog — portfolio furniture from openlimitsdesign.com until PDF/Excel import runs. */
export const fallbackFurnitureCatalog: FurnitureItem[] = [
  {
    id: "legacy-furn-majlis-suite",
    slug: "majlis-suite",
    title: "Majlis Suite",
    description:
      "Custom majlis seating with integrated side tables, premium upholstery, and brass detailing — designed for formal hospitality.",
    dimensions: "Modular — configured per room",
    width: null,
    depth: null,
    height: null,
    materials: "Velvet upholstery, solid wood frame, brushed brass",
    finishes: "Gold accent, deep neutral palette",
    features: "Modular layout, concealed storage options",
    availability: "Made to order",
    upholstery: "Velvet, linen, or leather options",
    collection: "Majlis Collection",
    category_id: "majlis",
    featured_image_id: media.majlisSuite.id,
    sort_order: 1,
    published: true,
    category: { id: "majlis", slug: "majlis", name: "Majlis", description: null, sort_order: 2, published: true },
    featured_image: media.majlisSuite,
    gallery: [media.majlisSuite],
    material_records: [legacyMaterials[0]]
  },
  {
    id: "legacy-furn-dining-collection",
    slug: "dining-collection",
    title: "Dining Collection",
    description:
      "Formal dining table with matching chairs and sideboard — stone top, sculpted legs, and coordinated lighting-ready layout.",
    dimensions: "Table 240 × 110 × 76 cm",
    width: "240 cm",
    depth: "110 cm",
    height: "76 cm",
    materials: "Marble top, oak base, upholstered dining chairs",
    finishes: "Natural stone, warm oak, neutral fabric",
    features: "Extendable configuration available",
    availability: "Made to order",
    upholstery: "Performance fabric or leather",
    collection: "Dining Collection",
    category_id: "tables",
    featured_image_id: media.diningCollection.id,
    sort_order: 2,
    published: true,
    category: { id: "tables", slug: "tables", name: "Tables", description: null, sort_order: 4, published: true },
    featured_image: media.diningCollection,
    gallery: [media.diningCollection],
    material_records: [legacyMaterials[0]]
  },
  {
    id: "legacy-furn-living-sofa",
    slug: "luxury-living-sofa",
    title: "Luxury Living Sofa",
    description:
      "Deep-seated sectional sofa with layered cushions and refined tailoring for open-plan living spaces.",
    dimensions: "320 × 105 × 85 cm",
    width: "320 cm",
    depth: "105 cm",
    height: "85 cm",
    materials: "Hardwood frame, high-resilience foam, premium fabric",
    finishes: "Matte wood base, contrast piping optional",
    features: "Modular sections, removable covers",
    availability: "In production",
    upholstery: "Bouclé, velvet, or leather",
    collection: "Living Collection",
    category_id: "sofas",
    featured_image_id: media.interiorLiving.id,
    sort_order: 3,
    published: true,
    category: { id: "sofas", slug: "sofas", name: "Sofas", description: null, sort_order: 1, published: true },
    featured_image: media.interiorLiving,
    gallery: [media.interiorLiving, media.heroInterior01],
    material_records: [legacyMaterials[0]]
  },
  {
    id: "legacy-furn-bedroom-suite",
    slug: "bedroom-suite",
    title: "Bedroom Suite",
    description:
      "Upholstered bed with integrated nightstands, wardrobe coordination, and soft ambient lighting planning.",
    dimensions: "King bed 200 × 220 cm",
    width: "200 cm",
    depth: "220 cm",
    height: "120 cm",
    materials: "Upholstered headboard, walnut veneer, brushed metal",
    finishes: "Warm neutrals, satin metal accents",
    features: "Custom headboard heights, integrated storage",
    availability: "Made to order",
    upholstery: "Linen, velvet, or leather headboard",
    collection: "Bedroom Collection",
    category_id: "bedrooms",
    featured_image_id: media.interiorBedroom.id,
    sort_order: 4,
    published: true,
    category: {
      id: "bedrooms",
      slug: "bedrooms",
      name: "Bedrooms",
      description: null,
      sort_order: 9,
      published: true
    },
    featured_image: media.interiorBedroom,
    gallery: [media.interiorBedroom],
    material_records: [legacyMaterials[0]]
  },
  {
    id: "legacy-furn-penthouse-lounge",
    slug: "penthouse-lounge-chair",
    title: "Penthouse Lounge Chair",
    description:
      "Sculptural lounge chair with curved silhouette — designed for penthouse lounges and hotel suites.",
    dimensions: "85 × 90 × 78 cm",
    width: "85 cm",
    depth: "90 cm",
    height: "78 cm",
    materials: "Solid wood, molded foam, premium upholstery",
    finishes: "Dark wood or light oak",
    features: "Swivel base optional",
    availability: "Made to order",
    upholstery: "Velvet, leather, or textured weave",
    collection: "Penthouse Collection",
    category_id: "chairs",
    featured_image_id: media.penthouseLounge.id,
    sort_order: 5,
    published: true,
    category: { id: "chairs", slug: "chairs", name: "Chairs", description: null, sort_order: 3, published: true },
    featured_image: media.penthouseLounge,
    gallery: [media.penthouseLounge, media.penthouseDetail],
    material_records: [legacyMaterials[0]]
  },
  {
    id: "legacy-furn-showroom-feature",
    slug: "signature-furniture-collection",
    title: "Signature Furniture Collection",
    description:
      "Curated showroom selection spanning sofas, tables, and accent pieces — fully customizable to project specifications.",
    dimensions: "Custom per piece",
    width: null,
    depth: null,
    height: null,
    materials: "Mixed noble materials — wood, stone, metal, fabric",
    finishes: "Project-specific palette",
    features: "FF&E specification support",
    availability: "Consultation required",
    upholstery: "Full fabric library access",
    collection: "Open Limits Signature",
    category_id: "sofas",
    featured_image_id: media.furnitureShowroom.id,
    sort_order: 6,
    published: true,
    category: { id: "sofas", slug: "sofas", name: "Sofas", description: null, sort_order: 1, published: true },
    featured_image: media.furnitureShowroom,
    gallery: [media.furnitureShowroom, media.majlisSuite, media.diningCollection],
    material_records: [legacyMaterials[0]]
  },
  {
    id: "legacy-furn-lusail-villa",
    slug: "lusail-villa-living-set",
    title: "Lusail Villa Living Set",
    description:
      "Complete living room FF&E package — sofa system, coffee table, and accent seating for a Lusail villa interior.",
    dimensions: "Room-specific layout",
    width: null,
    depth: null,
    height: null,
    materials: "Marble, oak, linen upholstery",
    finishes: "Coastal luxury palette",
    features: "Turnkey delivery and installation",
    availability: "Project-based",
    upholstery: "Linen and velvet combinations",
    collection: "Lusail Villa",
    category_id: "sofas",
    featured_image_id: media.lusailVilla01.id,
    sort_order: 7,
    published: true,
    category: { id: "sofas", slug: "sofas", name: "Sofas", description: null, sort_order: 1, published: true },
    featured_image: media.lusailVilla01,
    gallery: [media.lusailVilla01, media.lusailVilla02],
    material_records: [legacyMaterials[0]]
  },
  {
    id: "legacy-furn-jaz-residence",
    slug: "jaz-residence-dining",
    title: "JAZ Residence Dining Set",
    description:
      "Residential dining and lounge coordination for the JAZ Residence — warm materials and tailored proportions.",
    dimensions: "Table 220 × 100 × 75 cm",
    width: "220 cm",
    depth: "100 cm",
    height: "75 cm",
    materials: "Wood, stone, upholstered seating",
    finishes: "Warm contemporary",
    features: "Matched to architectural interiors",
    availability: "Project archive — replicable",
    upholstery: "Performance fabrics",
    collection: "JAZ Residence",
    category_id: "tables",
    featured_image_id: media.jazResidence.id,
    sort_order: 8,
    published: true,
    category: { id: "tables", slug: "tables", name: "Tables", description: null, sort_order: 4, published: true },
    featured_image: media.jazResidence,
    gallery: [media.jazResidence],
    material_records: [legacyMaterials[0]]
  }
];

export function getFallbackFurnitureBySlug(slug: string): FurnitureItem | null {
  return fallbackFurnitureCatalog.find((item) => item.slug === slug) ?? null;
}
